### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by SimonLopez-Volue-MarketServices** [ZinkNotTheMetal/Moq.RestSharp.Helpers#3]
I tried to run my code and I'm getting:

System.TypeLoadException : Type 'Castle.Proxies.IRestResponse`1Proxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=a621a9e7e5c32e69' is attempting to implement an inaccessible interface.

Can't find a sensible way to add or change the interface. I'll appreciate any help :)

**Comment by ZinkNotTheMetal** [comment]
Is your code on GitHub?

William

**Comment by ZinkNotTheMetal** [comment]
It looks like at a highlevel that you are trying to get your IRestResponse
dependency from Castle.Proxies which is not the namespace of mine.
Moq.RestSharp.Helpers

**Comment by mkrsbl** [comment]
No i dont.
But here are the involved files.

**Comment by SimonLopez-Volue-MarketServices** [comment]
[moq.helpers.zip](https://github.com/ZinkNotTheMetal/Moq.RestSharp.Helpers/files/6707275/moq.helpers.zip)

No i dont.
But here are the involved files.
fails on c.MockExecuteAsGet("GET");

**Comment by SimonLopez-Volue-MarketServices** [comment]
Update.

           //success on simple None Typed
            var response2 = MockRestClient
                .MockApiResponse()
                .WithStatusCode(HttpStatusCode.OK)
                .ReturnsJsonString("{ \"id\": 1,\"firstName\": \"Ut\", \"lastName\": \"Consectetur\" }")
                .MockExecuteAsGet("GET");

            Debug.Print("stop");

            //error on simple typed 
            var response = MockRestClient;
            var a = response.MockApiResponse<SwaggerApiToTest.Customer>();
            var b = a.WithStatusCode(HttpStatusCode.OK);
            var c = b.Returns(mockCustomer);
            var d = c.MockExecuteAsGet("GET");

**Comment by SimonLopez-Volue-MarketServices** [comment]
So it turns out that the proycall fails already at MockApiResponse when trying simple type example

Im referring to a customer not in same file as the MockApiResponse. It somehow cant handle it.
I moved my Customer class to my MoqHelpersTest. and it solved the error.
[MoqHelpersTest.zip](https://github.com/ZinkNotTheMetal/Moq.RestSharp.Helpers/files/6707733/MoqHelpersTest.zip)

**Comment by ZinkNotTheMetal** [comment]
Hmm, I'll check it out.
Glad you got it working! Hope it helps
