### ISSUE TITLE
How to mock different requests / responses with similar types?

### ISSUE THREAD

**Issue by benkoshy** [ZinkNotTheMetal/Moq.RestSharp.Helpers#4]
Hi William

Thank you for sharing your library / code.

> I hope this project helps you out with your unit testing endevours. If you need any help feel free to contact me.

I have a question re: your library:

```c#
public interface IPeopleRepository
{
    Task<List<Person>> GetPeopleFromRepository();
}

public class FakeApi : IPeopleRepository
{
    private readonly IRestClient _restClient;

    public FakeApi(IRestClient restClient)
    {
        _restClient = restClient;
    }

   public  void MakeManyRequests()
  {
        _restClient.Execute<TypeA>()(request1);
        _restClient.Execute<TypeA>()(request2); 
        _restClient.Execute<TypeB>()(request3);  // TypeB
  } 
}
```

This is essentially what is happening in my library (above):

I will be essentially making two responses that are of the same type (notice request1 and request2):

```c#
var response = MockRestClient
    .MockApiRequest<List<TypeA>>()
        .WithStatusCode(HttpStatusCode.InternalServerError)
        .WithResponseStatus(ResponseStatus.Error)
        .WithErrorMessage("API seems to be down at the moment, please try again later")
    .MockExecute();
```

I was wondering if there was some way I could mock both requests so that they return different values?

**Comment by ZinkNotTheMetal** [comment]
What is TypeA and TypeB?

Typically this library is used to return a single type not multiple with the same response.

**Comment by benkoshy** [comment]
Apologies my question was not clear. 

I have since lost familiarity with the problem.

Unless you have objections I will reopen if i have further questions?
